<a href="https://colab.research.google.com/github/prajwoldahal/AI-and-ML/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def convert_units(conversion_type, value):
    """
    Converts units based on the selected conversion type.

    Parameters:
    conversion_type (int): The type of conversion selected by user.
    value (float): The numeric value to convert.

    Returns:
    float: The converted value.
    """

    if conversion_type == 1:   # meters to feet
        return value * 3.28084
    elif conversion_type == 2: # feet to meters
        return value / 3.28084
    elif conversion_type == 3: # kg to pounds
        return value * 2.20462
    elif conversion_type == 4: # pounds to kg
        return value / 2.20462
    elif conversion_type == 5: # liters to gallons
        return value * 0.264172
    elif conversion_type == 6: # gallons to liters
        return value / 0.264172
    else:
        return None


#  Main Program
print("Unit Converter")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

try:
    choice = int(input("Choose conversion type (1-6): "))
    value = float(input("Enter value to convert: "))

    result = convert_units(choice, value)

    if result is None:
        print("Invalid conversion choice.")
    else:
        print("Converted value:", result)

except ValueError:
    print("Invalid input! Please enter numeric values only.")

Unit Converter
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose conversion type (1-6): 2
Enter value to convert: 2
Converted value: 0.6095999804928006


In [ ]:
#  Functions
def compute_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: Sum of the numbers.
    """
    return sum(numbers)


def compute_average(numbers):
    """
    Returns the average of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: Average of the numbers.
    """
    return sum(numbers) / len(numbers)


def compute_max(numbers):
    """
    Returns the maximum number in the list.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: Maximum value in the list.
    """
    return max(numbers)


def compute_min(numbers):
    """
    Returns the minimum number in the list.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: Minimum value in the list.
    """
    return min(numbers)


# Main Program
print("Math Operations on a List")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
    choice = int(input("Choose an operation (1-4): "))

    # Take input as a string and convert to a list of floats
    numbers_str = input("Enter numbers separated by spaces: ")
    numbers = [float(x) for x in numbers_str.split()]

    if len(numbers) == 0:
        print("Error: The list is empty.")
    else:
        if choice == 1:
            print("Sum:", compute_sum(numbers))
        elif choice == 2:
            print("Average:", compute_average(numbers))
        elif choice == 3:
            print("Maximum:", compute_max(numbers))
        elif choice == 4:
            print("Minimum:", compute_min(numbers))
        else:
            print("Invalid operation choice.")

except ValueError:
    print("Invalid input! Please enter numeric values only.")

Math Operations on a List
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 2
Enter numbers separated by spaces: 2 3
Average: 2.5


In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from the input list, starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element.
    """
    return lst[::2]


# Example Usage
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print("Original list:", numbers)
print("Every other element:", result)

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from index 'start' to 'end' (inclusive).

    Parameters:
    lst (list): Original list
    start (int): Starting index
    end (int): Ending index (inclusive)

    Returns:
    list: Sublist from start to end
    """
    return lst[start:end+1]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)

print("Original list:", numbers)
print("Sublist:", result)

Original list: [1, 2, 3, 4, 5, 6]
Sublist: [3, 4, 5]


In [ ]:
def reverse_list(lst):
  """
  Returns the reversed version of the given list using slicing.

    Parameters:
    lst (list): The original list

    Returns:
    list: Reversed list
    """
  return lst[::-1]
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)
print("Original list:", numbers)
print("Reversed list:", result)

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.
    """
    return lst[1:-1]
numbers = [1,2,3,4,5]
result = remove_first_last(numbers)
print("Original list:", numbers)
print("Sublist without first and last elements:", result)


Original list: [1, 2, 3, 4, 5]
Sublist without first and last elements: [2, 3, 4]


In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
    lst (list): The original list

    Returns:
    list: Sublist without the first and last elements
    """
    return lst[-1:1]
numbers = [1,2,3,4,5]
result = remove_first_last(numbers)
print("Original list:", numbers)
print("Sublist without first and last elements:", result)

Original list: [1, 2, 3, 4, 5]
Sublist without first and last elements: []


In [ ]:
def get_last_n(lst, n):
    """
    Returns the last n elements from a list using slicing.

    Parameters:
    lst (list): The original list
    n (int): Number of elements to extract from the end

    Returns:
    list: Last n elements of the list
    """
    return lst[-n:]


# Example
numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)

print("Original list:", numbers)
print("Last 2 elements:", result)

Original list: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


In [ ]:
def reverse_skip(lst):
    """
    Returns every second element from the list, starting from the second-to-last element,
    moving backward.

    Parameters:
    lst (list): The original list

    Returns:
    list: Elements in reverse, skipping one each time
    """
    return lst[-2::-2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print("Original list:", numbers)
print("Reverse skip list:", result)

Original list: [1, 2, 3, 4, 5, 6]
Reverse skip list: [5, 3, 1]


In [ ]:
"""1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5]."""

'1. Flatten a Nested List:\nWrite a Python function that takes a nested list and flattens it into a single list, where all the elements\nare in a single dimension.\n• Requirements:\n– Define a function flatten(lst) that takes a nested list lst and returns a flattened version\nof the list.\n– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].'

In [ ]:
def flatten(lst):
  """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): A nested list (list of lists)

    Returns:
    list: Flattened list containing all elements in a single dimension
  """
  return [i for j in lst for i in j]

nested_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(nested_list)

print('Original nested list:',nested_list)
print('Flattened list:',flattened_list)





Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """
    Accesses an element in a nested list using a list of indices.

    Parameters:
    lst (list): The nested list
    indices (list): A list of indices specifying the path to the element

    Returns:
    element: The element at the specified position
    """
    element = lst
    for idx in indices:
        element = element[idx]  # go one level deeper
    return element


# Example
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]  # access lst[1][2]
result = access_nested_element(nested_list, indices)

print("Nested list:", nested_list)
print(f"Element at indices {indices}:", result)

Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2]: 6


In [ ]:
def access_nested_element(lst, indices):
    """
    Access an element in a nested list using a list of indices.
    """
    for i in indices:
        lst = lst[i]
    return lst


nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)

print("Nested list:", nested_list)
print("Element at indices", indices, ":", result)

Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2] : 6


In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, regardless of depth.

    Parameters:
    lst (list): Nested list containing numbers or other lists

    Returns:
    int/float: Sum of all numbers in the nested list
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total



nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)

print("Nested list:", nested_list)
print("Sum of all elements:", result)


Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): Nested list
    elem: Element to remove

    Returns:
    list: Nested list with elem removed
    """
    result = []
    for i in lst:
        if isinstance(i, list):
            # Recursively process the sublist
            result.append(remove_element(i, elem))
        else:
            # Only keep i that are not equal to elem
            if i != elem:
                result.append(i)
    return result



nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2

new_list = remove_element(nested_list, element_to_remove)
print("Original list:", nested_list)
print("Modified list:", new_list)

Original list: [[1, 2], [3, 2], [4, 5]]
Modified list: [[1], [3], [4, 5]]


In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list.

    Parameters:
    lst (list): Nested list

    Returns:
    int/float: Maximum element
    """
    max_value = float('-inf')  # smallest possible starting value

    for item in lst:
        if isinstance(item, list):
            # Recursively find max in sublist
            sub_max = find_max(item)
            max_value = max(max_value, sub_max)
        else:
            max_value = max(max_value, item)

    return max_value


# Example
nested_list = [[1, 2], [3, [4, 5]], 6]
print(find_max(nested_list))  # Output: 6

6


In [ ]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): Nested list
    elem: Element to count

    Returns:
    int: Number of occurrences of elem
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            # Recursively count in sublist
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1

    return count


# Example
nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2

print(count_occurrences(nested_list, element_to_count))  # Output: 3

3


In [ ]:
def deep_flatten(lst):
    """
    Flattens a nested list of any depth into a single list.

    Parameters:
    lst (list): Nested list

    Returns:
    list: Flattened list
    """
    flat_list = []

    for item in lst:
        if isinstance(item, list):

            flat_list.extend(deep_flatten(item))
        else:

            flat_list.append(item)

    return flat_list


# Example
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_list))


[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
def average_nested(lst):
    # Flatten the list recursively
    flat_list = []

    for item in lst:
        if isinstance(item, list):
            flat_list.extend(average_nested(item))  # recursive flatten
        else:
            flat_list.append(item)

    return flat_list  # here we return flattened list first

In [ ]:
nested_list = [[1, 2], [3, 4], [5, 6]]

flat = average_nested(nested_list)
avg = sum(flat) / len(flat)

print(avg)

3.5


In [ ]:
import numpy as np

In [ ]:
empty_array = np.empty((2,2))
print(empty_array)

[[6.60935611e-310 3.92442240e-315]
 [1.75067506e-310 6.60935611e-310]]


In [ ]:
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
fill_value = 5
filled_array = np.full((3, 3), fill_value, dtype=int)
filled_array

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
given_array = np.array([[5, 6, 7], [8, 9, 10]])


zeros_like_array = np.zeros_like(given_array)

print(zeros_like_array)

[[0 0 0]
 [0 0 0]]


In [ ]:
new_list = [1,2,3,4]
new_array = np.array(new_list)
new_array

array([1, 2, 3, 4])

In [ ]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
array = np.arange(9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
matrix = array.reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
random_arr = np.random.random(30)
random_arr

array([0.91154872, 0.25158112, 0.09509837, 0.45801133, 0.27596749,
       0.491081  , 0.70219954, 0.60492305, 0.38272464, 0.38083558,
       0.81074068, 0.30994598, 0.41678486, 0.49724169, 0.49544514,
       0.16482019, 0.47688991, 0.31898279, 0.17536094, 0.04163602,
       0.80744896, 0.0420649 , 0.88223647, 0.4216834 , 0.13965827,
       0.68808117, 0.9194035 , 0.14527914, 0.25878251, 0.39666395])

In [ ]:
mean = np.mean(random_arr)
mean

np.float64(0.4321040436096383)

In [ ]:
random_matrix = np.random.rand(10,10)
random_matrix

array([[9.83816711e-01, 6.47448597e-01, 3.49120653e-01, 1.53196965e-01,
        8.50581421e-01, 1.56274754e-01, 5.16577719e-01, 6.13398942e-01,
        7.94760005e-02, 1.85953374e-01],
       [3.13122603e-01, 5.10066496e-01, 5.69803785e-01, 3.34112391e-01,
        9.74771289e-01, 1.67433798e-01, 8.23555709e-01, 6.64413043e-01,
        5.51720118e-01, 8.07697944e-02],
       [9.27390045e-01, 7.40671815e-01, 7.19191840e-01, 4.65008662e-01,
        9.00651205e-01, 7.31909847e-01, 8.47034114e-01, 2.28480833e-01,
        5.34057465e-01, 7.90826272e-02],
       [5.11326799e-01, 8.26241111e-01, 2.11765286e-01, 8.30183085e-01,
        2.76290513e-02, 4.34971494e-01, 4.95642115e-01, 4.87679958e-01,
        4.52334151e-01, 8.93493567e-01],
       [3.36805329e-01, 4.76091799e-01, 8.38766159e-01, 4.86885635e-02,
        9.23149422e-01, 9.76374777e-01, 6.12361781e-01, 3.29304886e-01,
        4.30914171e-01, 2.30254377e-01],
       [4.02516185e-01, 1.30422529e-01, 7.68124050e-01, 5.69010512e-02,
   

In [ ]:
max = np.max(random_matrix)
max

np.float64(0.9968353775282089)

In [ ]:
min = np.min(random_matrix)
min

np.float64(0.0005586980852195778)

In [ ]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
arr = [1,2,0,0,4,0]
arr = arr[::-1]
arr


[0, 4, 0, 0, 2, 1]

In [ ]:
array = np.ones((5,5))
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
array[1:-1,1:-1] = 0
array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr = np.zeros((8,8), dtype=int)

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [ ]:
add = x + y
add

array([[ 6,  8],
       [10, 13]])

In [ ]:
sub = x - y
sub

array([[-4, -4],
       [-4, -3]])

In [ ]:
mul = x * 2
mul

array([[ 2,  4],
       [ 6, 10]])

In [ ]:
square = y **2
square

array([[25, 36],
       [49, 64]])

In [ ]:
np.dot(v, w)

np.int64(219)

In [ ]:
np.dot(v, w)

np.int64(219)

In [ ]:
np.dot(x, y)

array([[19, 22],
       [50, 58]])